name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: restart the service
        run: sudo systemctl restart fastapi_demo



