name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Open Web Client Directory
        run: |
          ls -la

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          script: |
            echo 'Deployment to digital ocean finished'
          
      - name: restart the service
        working-directory: /usr/local/bin/home
        run: sudo systemctl restart fastapi_demo



