name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Open Web Client Directory
        run: |
          ls -la

     - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v


