name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Open Web Client Directory
        run: |
          ls -la
          
      - name: restart the service
        working-directory: /usr/local/bin/home
        run: sudo systemctl restart fastapi_demo



