name: Continuous Integration

on:
  # pull_request:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-22.04
    steps:

      - name: Open Web Client Directory
        run: |
          ls -la


