name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  merge_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: restart the service
        run: sudo systemctl start fastapi_demo



